### ISSUE TITLE
Bug surcharge chance max chapitre 35

### ISSUE THREAD

**Issue by Holorim** [naparuba/fdcn#12]
Bonjour.

J'ai commencé mon aventure en tant que billy paysan et un souci arrivé au chapitre 35 de la forteresse du chaudron noir. J'ai, en me promenant dans l'appli, accidentellement reboot mon histoire en appuyant sur Nouveau billy. J'ai donc rebuild mon billy et réavancé dans l'histoire. Mais la chance max ne semble pas rebootée dans ce cas et une fois au chapitre 35 on gagne une chance max.

Du coup on peut farmer la chance max en chargeant en boucle le chapitre 35.

Se serait bien que quand on clique sur nouveau billy cela vide toutes les stats acquises afin de pouvoir repartir propre. Parce que en rechargeant un nouveau billy à chaque fois j'ai pu monter à 9 de chance max et je pourrais si je voulais avoir chance max infinie.

**Comment by naparuba** [comment]
Bonjour,

merci du retour, en effet c'est un soucis ^^
Je suis bientôt en congés, je vais pouvoir régler ça je pense. Le soucis du reboot accidentel devrait être réglé également, quelqu'un a proposé du code pour le fixer :p

**Comment by naparuba** [comment]
Pour info je viens de commit une amélioration de @linklinsse qui permet de prévenir avant de reboot son perso ^^
Ca sera donc dans la prochaine version.

Je regarde quand même cette historie de reset, car bon chance infinie c'est un peu too much quand même, Billy est chanceux mais pas autant que ça tout de même

**Comment by naparuba** [comment]
Et hop fix commité, je te rajoute dans les remerciements et je build une nouvelle version 👍

**Comment by Holorim** [comment]
Bonjour.

J'ai remarqué en faisant quelques tests que:

- un reset de personnage et un go fast au chapitre 35 incrémenter de 1 la chance max.
- si on créé un nouveau perso puis que l'on ferme l'appli et qu'on la réouvre il me semble que ça doit vider un cache parce que j'étais revenu à des stats correctes mais je sais plus comment.

Il se peut que la valeur soit gardée en cache quelque part du coup.

Merci à vous.
