### ISSUE TITLE
Bug #65

### ISSUE THREAD

**Issue by Mystorage09** [naparuba/fdcn#6]
Au chapitre 65, le livre met en Vert le choix 244 à condition d'avoir soit le pamphlet, soit être paysan, soit être débrouillard, or il faut le pamphlet ET être un paysan ou un débrouillard pour aller en 65 
Excellente application cependant continue c'est génial 👌

**Comment by naparuba** [comment]
Merci j'ai changé la règle en KIT DE SOIN&(PAYSAN|DEBROUILLARD)
Comme quoi j'ai bien fait de coder un système de règle complexe ^^

Je vais builder une nouvelle version, il y avait aussi un autre saut qui manquait (suite au quartier boulanger, quand on peux sauter à la forteresse)


Encore merci pour le ticket et la description claire :)

**Comment by naparuba** [comment]
Build fait, app en cours d'analyse par google play (ça prends entre quelques heures à 2 jours, c'est variable).

Si tu vois le moindre soucis, n'hésites pas à poster un autre ticket :)

Encore merci,


Jean

**Comment by Mystorage09** [comment]
Nickel 👌 j'ai posté aussi un autre "bug" à propos des PV max qui augmente lorsque le personnage est soigné alors qu'il a déjà ses PV au maximum
