### ISSUE TITLE
De 184 vers 581

### ISSUE THREAD

**Issue by polurax** [naparuba/fdcn#8]
Pour passer de la plate-forme à la tour sud, il faut le kit d'escalade dans les deux sens. Or, il n'est demandé que dans un seul sur l'appli

**Comment by naparuba** [comment]
Merci du retour, je vais regarder ça ^^

**Comment by naparuba** [comment]
En effet, en le relisant j'ai pris le kit pour juste la tour nord, mais pas pour la tour sud, alors que bon, faut avouer que la tour, faut bien un bon gros kit pour la monter :p 

Je fixe ça.

**Comment by naparuba** [comment]
Hop fixé, bientôt sur google play :)
